### ISSUE TITLE
how to install it?

### ISSUE THREAD

**Issue by Harliff** [gerasiov/ofxstatement-russian#1]
How to install "ofxstatement-russian" to /usr/local? 
"Make" only installed it in ~/tmp/ofxstatement-russian/.venv" directory.

Could you please add installation instructions to the documentation?

**Comment by gerasiov** [comment]
You need to install it the same way you install ofxstatement.

Please see https://github.com/kedder/ofxstatement for some information. Or python's docs here: https://docs.python.org/3/installing/

On Debian (and Ubuntu) system you could just install ofxstatement and ofxstatement-plugins as deb-packages from official repositories.
